# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#
Category.create({id: 50, name: 'Alimentos, Bebidas y Tabaco'})
Category.create({id: 15, name: 'Combustibles, Aditivos para combustibles, Lubricantes y Materiales Anticorrosivos'})
Category.create({id: 31, name: 'Componentes y Suministros de Fabricacion'})
Category.create({id: 30, name: 'Componentes y Suministros de Fabricacion, Estructuras, Obras y Construcciones'})
Category.create({id: 32, name: 'Componentes y Suministros Electrónicos'})
Category.create({id: 95, name: 'CSS-MINSA'})
Category.create({id: 41, name: 'Equipo de Laboratorio, Medida, Observación y Comprobación'})
Category.create({id: 45, name: 'Equipo y Suministros de Imprenta, Fotográficos y Audiovisuales'})
Category.create({id: 47, name: 'Equipo y Suministros de limpieza'})
Category.create({id: 44, name: 'Equipo, Accesorios y Suministros de Oficina'})
Category.create({id: 42, name: 'Equipo, Accesorios y Suministros Médicos'})
Category.create({id: 46, name: 'Equipos y Suministros de Defensa, Orden Público, Protección y Seguridad'})
Category.create({id: 49, name: 'Equipos, suministros y accesorios deportivos y recreativos'})
Category.create({id: 27, name: 'Herramientas y Maquinaria en General'})
Category.create({id: 60, name: 'Instrumentos musicales, juegos, juguetes, artesanía y equipamiento, material, accesorios y suministros para educación'})
Category.create({id: 20, name: 'Maquinaria de minería y perforación de pozos y accesorios'})
Category.create({id: 23, name: 'Maquinaria y Accesorios de Fabricación y Transformación Industrial'})
Category.create({id: 21, name: 'Maquinaria y Accesorios para Agricultura, Pesca, Silvicultura y Fauna.'})
Category.create({id: 22, name: 'Maquinaria y Accesorios para Construcción y Edificación'})
Category.create({id: 26, name: 'Maquinaria y Accesorios para Generación y Distribución de Energía'})
Category.create({id: 24, name: 'Maquinaria, Accesorios y Suministros para Manejo, Acondicionamiento y Almacenamiento de Materiales'})
Category.create({id: 48, name: 'Maquinaria, Equipo y Suministros para la Industria de Servicios'})
Category.create({id: 10, name: 'Material, Accesorios y Suministros de Plantas y Animales Vivos'})
Category.create({id: 11, name: 'Materiales de Minerales y Tejidos y de Plantas y Animales no Comestibles'})
Category.create({id: 14, name: 'Materiales y Productos de Papel'})
Category.create({id: 51, name: 'Medicamentos y Productos Farmacéuticos'})
Category.create({id: 56, name: 'Muebles y mobiliario'})
Category.create({id: 52, name: 'Muebles, Accesorios, Electrodomésticos y Productos Electrónicos de Consumo'})
Category.create({id: 94, name: 'Organizaciones y Clubes'})
Category.create({id: 54, name: 'Productos para Relojería, Joyería y Gemas'})
Category.create({id: 55, name: 'Productos Publicados'})
Category.create({id: 12, name: 'Productos químicos incluyendo los bio-químicos y gases industriales'})
Category.create({id: 13, name: 'Resina y Colofonia y Caucho y Espuma y Película y Materiales Elastoméricos'})
Category.create({id: 53, name: 'Ropa, Maletas y Productos de Aseo Personal'})
Category.create({id: 81, name: 'Servicios basados en ingeniería, investigación y tecnología'})
Category.create({id: 72, name: 'Servicios de Construcción y Mantenimiento'})
Category.create({id: 70, name: 'Servicios de Contratación Agrícola, Pesquera, Forestal y de Fauna'})
Category.create({id: 92, name: 'Servicios de Defensa Nacional, Orden Público y Seguridad'})
Category.create({id: 80, name: 'Servicios de Gestión, Profesionales de Empresa y Administrativos'})
Category.create({id: 76, name: 'Servicios de Limpieza Industrial'})
Category.create({id: 71, name: 'Servicios de Perforación de Minería, Petróleo y Gas'})
Category.create({id: 73, name: 'Servicios de Producción y Fabricación Industrial'})
Category.create({id: 78, name: 'Servicios de Transporte, Almacenaje y Correo'})
Category.create({id: 90, name: 'Servicios de Viajes, Alimentación, Alojamiento y Entretenimiento'})
Category.create({id: 82, name: 'Servicios Editoriales, de Diseño, Gráficos y de Bellas Artes'})
Category.create({id: 86, name: 'Servicios Educativos y de Formación'})
Category.create({id: 84, name: 'Servicios Financieros y de Seguros'})
Category.create({id: 77, name: 'Servicios Medioambientales'})
Category.create({id: 91, name: 'Servicios Personales y Domésticos'})
Category.create({id: 93, name: 'Servicios Políticos y de Asuntos Cívicos'})
Category.create({id: 83, name: 'Servicios Públicos y Servicios Relacionados con el Sector Público'})
Category.create({id: 85, name: 'Servicios Sanitarios'})
Category.create({id: 40, name: 'Sistemas, Equipos y Componentes de Distribución y Acondicionamiento'})
Category.create({id: 39, name: 'Suministros, componentes y accesorios eléctricos y de iluminación'})
Category.create({id: 43, name: 'Telecomunicaciones y radiodifusión de tecnología de la información'})
Category.create({id: 25, name: 'Vehículos Comerciales, Militares y Particulares, Accesorios y Component'})

