require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AsociationsController do

  # This should return the minimal set of attributes required to create a valid
  # Asociation. As you add validations to Asociation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "persona_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AsociationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all asociations as @asociations" do
      asociation = Asociation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:asociations).should eq([asociation])
    end
  end

  describe "GET show" do
    it "assigns the requested asociation as @asociation" do
      asociation = Asociation.create! valid_attributes
      get :show, {:id => asociation.to_param}, valid_session
      assigns(:asociation).should eq(asociation)
    end
  end

  describe "GET new" do
    it "assigns a new asociation as @asociation" do
      get :new, {}, valid_session
      assigns(:asociation).should be_a_new(Asociation)
    end
  end

  describe "GET edit" do
    it "assigns the requested asociation as @asociation" do
      asociation = Asociation.create! valid_attributes
      get :edit, {:id => asociation.to_param}, valid_session
      assigns(:asociation).should eq(asociation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Asociation" do
        expect {
          post :create, {:asociation => valid_attributes}, valid_session
        }.to change(Asociation, :count).by(1)
      end

      it "assigns a newly created asociation as @asociation" do
        post :create, {:asociation => valid_attributes}, valid_session
        assigns(:asociation).should be_a(Asociation)
        assigns(:asociation).should be_persisted
      end

      it "redirects to the created asociation" do
        post :create, {:asociation => valid_attributes}, valid_session
        response.should redirect_to(Asociation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved asociation as @asociation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Asociation.any_instance.stub(:save).and_return(false)
        post :create, {:asociation => { "persona_id" => "invalid value" }}, valid_session
        assigns(:asociation).should be_a_new(Asociation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Asociation.any_instance.stub(:save).and_return(false)
        post :create, {:asociation => { "persona_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested asociation" do
        asociation = Asociation.create! valid_attributes
        # Assuming there are no other asociations in the database, this
        # specifies that the Asociation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Asociation.any_instance.should_receive(:update).with({ "persona_id" => "1" })
        put :update, {:id => asociation.to_param, :asociation => { "persona_id" => "1" }}, valid_session
      end

      it "assigns the requested asociation as @asociation" do
        asociation = Asociation.create! valid_attributes
        put :update, {:id => asociation.to_param, :asociation => valid_attributes}, valid_session
        assigns(:asociation).should eq(asociation)
      end

      it "redirects to the asociation" do
        asociation = Asociation.create! valid_attributes
        put :update, {:id => asociation.to_param, :asociation => valid_attributes}, valid_session
        response.should redirect_to(asociation)
      end
    end

    describe "with invalid params" do
      it "assigns the asociation as @asociation" do
        asociation = Asociation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Asociation.any_instance.stub(:save).and_return(false)
        put :update, {:id => asociation.to_param, :asociation => { "persona_id" => "invalid value" }}, valid_session
        assigns(:asociation).should eq(asociation)
      end

      it "re-renders the 'edit' template" do
        asociation = Asociation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Asociation.any_instance.stub(:save).and_return(false)
        put :update, {:id => asociation.to_param, :asociation => { "persona_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested asociation" do
      asociation = Asociation.create! valid_attributes
      expect {
        delete :destroy, {:id => asociation.to_param}, valid_session
      }.to change(Asociation, :count).by(-1)
    end

    it "redirects to the asociations list" do
      asociation = Asociation.create! valid_attributes
      delete :destroy, {:id => asociation.to_param}, valid_session
      response.should redirect_to(asociations_url)
    end
  end

end
