require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LicitationsController do

  # This should return the minimal set of attributes required to create a valid
  # Licitation. As you add validations to Licitation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "url" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LicitationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all licitations as @licitations" do
      licitation = Licitation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:licitations).should eq([licitation])
    end
  end

  describe "GET show" do
    it "assigns the requested licitation as @licitation" do
      licitation = Licitation.create! valid_attributes
      get :show, {:id => licitation.to_param}, valid_session
      assigns(:licitation).should eq(licitation)
    end
  end

  describe "GET new" do
    it "assigns a new licitation as @licitation" do
      get :new, {}, valid_session
      assigns(:licitation).should be_a_new(Licitation)
    end
  end

  describe "GET edit" do
    it "assigns the requested licitation as @licitation" do
      licitation = Licitation.create! valid_attributes
      get :edit, {:id => licitation.to_param}, valid_session
      assigns(:licitation).should eq(licitation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Licitation" do
        expect {
          post :create, {:licitation => valid_attributes}, valid_session
        }.to change(Licitation, :count).by(1)
      end

      it "assigns a newly created licitation as @licitation" do
        post :create, {:licitation => valid_attributes}, valid_session
        assigns(:licitation).should be_a(Licitation)
        assigns(:licitation).should be_persisted
      end

      it "redirects to the created licitation" do
        post :create, {:licitation => valid_attributes}, valid_session
        response.should redirect_to(Licitation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved licitation as @licitation" do
        # Trigger the behavior that occurs when invalid params are submitted
        Licitation.any_instance.stub(:save).and_return(false)
        post :create, {:licitation => { "url" => "invalid value" }}, valid_session
        assigns(:licitation).should be_a_new(Licitation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Licitation.any_instance.stub(:save).and_return(false)
        post :create, {:licitation => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested licitation" do
        licitation = Licitation.create! valid_attributes
        # Assuming there are no other licitations in the database, this
        # specifies that the Licitation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Licitation.any_instance.should_receive(:update).with({ "url" => "MyString" })
        put :update, {:id => licitation.to_param, :licitation => { "url" => "MyString" }}, valid_session
      end

      it "assigns the requested licitation as @licitation" do
        licitation = Licitation.create! valid_attributes
        put :update, {:id => licitation.to_param, :licitation => valid_attributes}, valid_session
        assigns(:licitation).should eq(licitation)
      end

      it "redirects to the licitation" do
        licitation = Licitation.create! valid_attributes
        put :update, {:id => licitation.to_param, :licitation => valid_attributes}, valid_session
        response.should redirect_to(licitation)
      end
    end

    describe "with invalid params" do
      it "assigns the licitation as @licitation" do
        licitation = Licitation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Licitation.any_instance.stub(:save).and_return(false)
        put :update, {:id => licitation.to_param, :licitation => { "url" => "invalid value" }}, valid_session
        assigns(:licitation).should eq(licitation)
      end

      it "re-renders the 'edit' template" do
        licitation = Licitation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Licitation.any_instance.stub(:save).and_return(false)
        put :update, {:id => licitation.to_param, :licitation => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested licitation" do
      licitation = Licitation.create! valid_attributes
      expect {
        delete :destroy, {:id => licitation.to_param}, valid_session
      }.to change(Licitation, :count).by(-1)
    end

    it "redirects to the licitations list" do
      licitation = Licitation.create! valid_attributes
      delete :destroy, {:id => licitation.to_param}, valid_session
      response.should redirect_to(licitations_url)
    end
  end

end
