require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OwnerBrandsController do

  # This should return the minimal set of attributes required to create a valid
  # OwnerBrand. As you add validations to OwnerBrand, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OwnerBrandsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all owner_brands as @owner_brands" do
      owner_brand = OwnerBrand.create! valid_attributes
      get :index, {}, valid_session
      assigns(:owner_brands).should eq([owner_brand])
    end
  end

  describe "GET show" do
    it "assigns the requested owner_brand as @owner_brand" do
      owner_brand = OwnerBrand.create! valid_attributes
      get :show, {:id => owner_brand.to_param}, valid_session
      assigns(:owner_brand).should eq(owner_brand)
    end
  end

  describe "GET new" do
    it "assigns a new owner_brand as @owner_brand" do
      get :new, {}, valid_session
      assigns(:owner_brand).should be_a_new(OwnerBrand)
    end
  end

  describe "GET edit" do
    it "assigns the requested owner_brand as @owner_brand" do
      owner_brand = OwnerBrand.create! valid_attributes
      get :edit, {:id => owner_brand.to_param}, valid_session
      assigns(:owner_brand).should eq(owner_brand)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OwnerBrand" do
        expect {
          post :create, {:owner_brand => valid_attributes}, valid_session
        }.to change(OwnerBrand, :count).by(1)
      end

      it "assigns a newly created owner_brand as @owner_brand" do
        post :create, {:owner_brand => valid_attributes}, valid_session
        assigns(:owner_brand).should be_a(OwnerBrand)
        assigns(:owner_brand).should be_persisted
      end

      it "redirects to the created owner_brand" do
        post :create, {:owner_brand => valid_attributes}, valid_session
        response.should redirect_to(OwnerBrand.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved owner_brand as @owner_brand" do
        # Trigger the behavior that occurs when invalid params are submitted
        OwnerBrand.any_instance.stub(:save).and_return(false)
        post :create, {:owner_brand => {  }}, valid_session
        assigns(:owner_brand).should be_a_new(OwnerBrand)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OwnerBrand.any_instance.stub(:save).and_return(false)
        post :create, {:owner_brand => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested owner_brand" do
        owner_brand = OwnerBrand.create! valid_attributes
        # Assuming there are no other owner_brands in the database, this
        # specifies that the OwnerBrand created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OwnerBrand.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => owner_brand.to_param, :owner_brand => { "these" => "params" }}, valid_session
      end

      it "assigns the requested owner_brand as @owner_brand" do
        owner_brand = OwnerBrand.create! valid_attributes
        put :update, {:id => owner_brand.to_param, :owner_brand => valid_attributes}, valid_session
        assigns(:owner_brand).should eq(owner_brand)
      end

      it "redirects to the owner_brand" do
        owner_brand = OwnerBrand.create! valid_attributes
        put :update, {:id => owner_brand.to_param, :owner_brand => valid_attributes}, valid_session
        response.should redirect_to(owner_brand)
      end
    end

    describe "with invalid params" do
      it "assigns the owner_brand as @owner_brand" do
        owner_brand = OwnerBrand.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OwnerBrand.any_instance.stub(:save).and_return(false)
        put :update, {:id => owner_brand.to_param, :owner_brand => {  }}, valid_session
        assigns(:owner_brand).should eq(owner_brand)
      end

      it "re-renders the 'edit' template" do
        owner_brand = OwnerBrand.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OwnerBrand.any_instance.stub(:save).and_return(false)
        put :update, {:id => owner_brand.to_param, :owner_brand => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested owner_brand" do
      owner_brand = OwnerBrand.create! valid_attributes
      expect {
        delete :destroy, {:id => owner_brand.to_param}, valid_session
      }.to change(OwnerBrand, :count).by(-1)
    end

    it "redirects to the owner_brands list" do
      owner_brand = OwnerBrand.create! valid_attributes
      delete :destroy, {:id => owner_brand.to_param}, valid_session
      response.should redirect_to(owner_brands_url)
    end
  end

end
